### ISSUE TITLE
Deliverables by 3/29

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#15]
SERVER SIDE (DRUPAL COMMONS)

Create an alternate Form branch for testing form with only username and page URL.

**Comment by elisseck** [comment]
How should we handle "page two", technically? Should the data from page 1 "submit" automatically when you move to page two? 

If not ... Should you be able to switch back and forth between the pages or have it be a linear process?

I think it's pretty easy to make any of these things happen ... just curious what you have in mind.

**Comment by bmoreinis** [comment]
I was envisioning page two as populating the same JSON object, which 
would be stored locally (or via cookie) at the end of page one, when 
clicking the "Page Two" button.

None of the Page Two fields should be required ... so we can leave the 
"Submit" button as is.


-- 

Martin Bram Moreinis, Designer/Developer
http://myinstructionaldesigns.com
(413) 829-0355

**Comment by elisseck** [comment]
This is what i'm thinking (for efficiency) - page two will populate the same JSON object... but rather than monkeying around saving and retrieving the data from page 1 - we just leave it in-form, hide the original form div, and populate page 2 in its place (with a new submit button that will submit both sets of data invoking the original submit function + some extra stuff).

Does anything about that strategy ring alarm bells for you?

**Comment by bmoreinis** [comment]
Smashing.  My only concern is, what if they hit the BACK button because 
they want to go back and edit the first form?  But that would be an 
issue either way ... Let's warn them:

|window.onbeforeunload =function(){return"You work will be lost.";};|

**Comment by elisseck** [comment]
Sounds good.

One further question:

Is page 2 intended to be a static set of questions or should it be created dynamically in a way that's easy to add/remove questions like we did for the original form?

**Comment by bmoreinis** [comment]
Dynamic.  Mostly multi-line text fields.


On 3/20/2017 2:01 PM, Eli Lisseck wrote:
> Is page 2 intended to be a static set of questions or should it be 
> created dynamically in a way that's easy to add/remove questions like 
> we did for the original form?

-- 

Martin Bram Moreinis, Designer/Developer
http://myinstructionaldesigns.com
(413) 829-0355

**Comment by bmoreinis** [comment]
Eli - I pulled out the Extension issues so comments can follow them, devoted this only to Drupal issues (except 0).

**Comment by bmoreinis** [comment]
Fork is on hackforwesternmass.  Using git bash for local fork.

**Comment by bmoreinis** [comment]
1. Is done = Simplified form via the HackforWesternMass version, tested on database.  Ready for 2. Drupal.

**Comment by bmoreinis** [comment]
Closing issue - the alternate branch is being forked and handled on http://github/hackforwesternmass/fakenews
