### ISSUE TITLE
Bug: linkfinder is not working as expected

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#16]
Very hard to explain in a non-long-winded fashion but i've found in some cases linkfinder() crashes because it's iterating too many times and running into _undefined_.children and can't evaluate... and in some cases it fails to iterate enough times to find all links inside <p> tags.

**Comment by bmoreinis** [comment]
Yes, I'm aware of that.  It happens on the home page of http://martinlutherking.org, in fact.  I'm okay with this behavior at the moment - would rather be able to demo full functionality than get one piece perfect.  But definitely keep it an issue to grab at. 

Should I replicate issues in Open Atrium as tasks, or just leave all this here?

**Comment by elisseck** [comment]
I'm happy with the issues staying here with the project, with the idea that OA is kind of higher level for documenting new learning and new projects.

**Comment by bmoreinis** [comment]
OK! (I think I asked you that once before and you told me that same 
answer. <sigh>)

**Comment by elisseck** [comment]
I think this is fixed. I wrote a thing like a real dummy :).

Let's reopen if it's still not working correctly.
