### ISSUE TITLE
Prune Parameters from URL, put in separate form field. 

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#24]
Prune the parameters from the URL and put them in a separate form field.   This gives user information about someone caring about who gets to the page, perhaps. 

(http://www.gilliganondata.com/index.php/2012/05/22/the-anatomy-of-a-url-protocol-hostname-path-and-parameters/)

**Comment by elisseck** [comment]
Oh I see we actually want them in a separate field? I just pruned them off period. This will be a pretty easy fix, I think.
