### ISSUE TITLE
Listed links bleed over background of floating form

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#3]
As below - when links are longer than the background is wide... they simply bleed over onto the page and you can't read them.

![image](https://cloud.githubusercontent.com/assets/12917373/22605189/bdd96294-ea1c-11e6-96f8-a1c795f63c3d.png)

**Comment by bmoreinis** [comment]
My goal is to have the output form be full-page, 50% of vertical space 
with scrollbars.

**Comment by bmoreinis** [comment]
I fixed this with my commit on Tuesday.
