### ISSUE TITLE
Interesting CSS issue

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#33]
Low low low priority and there probably isn't any way we can anticipate all of these things... but I noticed some strange focusing behavior with the buttons on the fakenewsfitness commons page:

![image](https://cloud.githubusercontent.com/assets/12917373/24368250/b51f9c78-12ed-11e7-9df3-b312d2b47c3e.png)

**Comment by deltafactory** [comment]
Is this still an issue? Something to revisit with the new styling, if so.

**Comment by deltafactory** [comment]
N/A
