### ISSUE TITLE
How should OG population work?

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#37]
Questions I have to get this working with OG since I don't know the entire drupal structure you are planning :) :

1) OG is supposed to be based on the group/s that the user is in based on the email they input, correct?

2) will someone ever have more than 1 OG?

2.5) if so, how should we determine which one is selected?

3) will someone ever have zero OGs?

4) how should (if at all) the Chrome extension deal with the "choose your own adventure" free input OG field?

Thanks!

**Comment by bmoreinis** [comment]
There are 2 OG Structures:  Project (for which a Page Check is a content type) and Class (for which a User is a content type).  So there should never be more than 1 OG for a node or user, BUT through entity relations there are associations. 

This means that a user could, conceivably, be a member of more than one group, and it would be impossible to tell, from the user name, which group to assign the content to. 

I think the only feasible way to do this is to hard-code a group ID into the Chrome extension, and distribute that extension project-by-project.  The form title indicates project so we know where we're at.  

Another advantage is that we can customize which fields go into which projects. 

Sound good ?

**Comment by elisseck** [comment]
Sounds good to me! Definitely a good starting place at the very least.

We do grab the whole user object because that's how restws responds... so if anything in there helps, we do have access to it.

**Comment by bmoreinis** [comment]
Hmmmm.... well if the user object includes groups the user is a member of, then we could do something easier.  We know that because the user created the content, the user's class group will control access ... so the main question is what group the user is a member of.  If the RestWS response includes that, then we just apply the first one it offers as a default.  

Does it?

**Comment by elisseck** [comment]
Here is everything I am getting from my own user object that is related to OG.. I haven't really had time to unpack this yet so maybe I shouldn't have mentioned it yet haha. Do you know what the OG membership id's correspond to or how I can look those up to see what it all means? I haven't configured OG before:

"og_user_user": [],
"og_membership": [
  {
"uri": "http://www.fakenewsfitness.org/og_membership/3",
"id": 3,
"resource": "og_membership"
},
  {
"uri": "http://www.fakenewsfitness.org/og_membership/7",
"id": 7,
"resource": "og_membership"
},
  {
"uri": "http://www.fakenewsfitness.org/og_membership/9",
"id": 9,
"resource": "og_membership"
}
],
"og_membership__1": [
  {
"uri": "http://www.fakenewsfitness.org/og_membership/3",
"id": 3,
"resource": "og_membership"
},
  {
"uri": "http://www.fakenewsfitness.org/og_membership/7",
"id": 7,
"resource": "og_membership"
},
  {
"uri": "http://www.fakenewsfitness.org/og_membership/9",
"id": 9,
"resource": "og_membership"
}
],
"og_membership__2": [],
"og_membership__3": [],
"og_user_node__og_membership": [
  {
"uri": "http://www.fakenewsfitness.org/og_membership/7",
"id": 7,
"resource": "og_membership"
},
  {
"uri": "http://www.fakenewsfitness.org/og_membership/9",
"id": 9,
"resource": "og_membership"
}
],
"og_user_node__og_membership__1": [
  {
"uri": "http://www.fakenewsfitness.org/og_membership/7",
"id": 7,
"resource": "og_membership"
},
  {
"uri": "http://www.fakenewsfitness.org/og_membership/9",
"id": 9,
"resource": "og_membership"
}
],
"og_user_node__og_membership__2": [],
"og_user_node__og_membership__3": [],
"user_trusted_contacts__og_membership": [
  {
"uri": "http://www.fakenewsfitness.org/og_membership/3",
"id": 3,
"resource": "og_membership"
}
],
"user_trusted_contacts__og_membership__1": [
  {
"uri": "http://www.fakenewsfitness.org/og_membership/3",
"id": 3,
"resource": "og_membership"
}
],
"user_trusted_contacts__og_membership__2": [],
"user_trusted_contacts__og_membership__3": [],
"og_user_user__og_membership": [],
"og_user_user__og_membership__1": [],
"og_user_user__og_membership__2": [],
"og_user_user__og_membership__3": [],

**Comment by bmoreinis** [comment]
If you navigate to a group and hover over "edit" you'll see the group's node ID.  There is also a Group ID.  So if you go to the home page of the Development project group, http://www.fakenewsfitness.org/groups/development, hovering over Edit shows this is Node 1.  The class group, MoreinisELA10, is Node 3. 

To get the Group ID, that's tricky.  There are code ways (so you create a custom PHP Blog to display them - http://drupal.stackexchange.com/questions/23461/how-can-i-get-the-group-id-of-a-node) and there are Views ways (so create a Views Panel Pane with that). 

That's all I know!

**Comment by elisseck** [comment]
hard coding and closing for now - until I have time to learn more.
