### ISSUE TITLE
Should date modified field populate time?

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#4]
Currently, when asked to the date modified field populates the entire date object with time if it is using the document.modified input (static pages only).

I've found that the day matches well, but the time doesn't always match (on wikipedia for example, compared to the entry at the bottom of the page the date matches but the time does not).

The difference in time could be confusing to users?

**Comment by bmoreinis** [comment]
Can we just limit the characters to show only day, rather than hour, in 
output?

**Comment by elisseck** [comment]
Should be patched up with [this commit](https://github.com/bmoreinis/fakenews/commit/d447272ca929af82fce77b8f5e46d8675873c1fe)
