### ISSUE TITLE
New Branch AllFieldsLeadToDrupal ready for testing by someone other than myself

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#42]
There are so many possible input values that I feel like I need one other tester who hasn't written the code to try to break it! Will you give it some input and tell me what your thoughts and/or errors are?

Still to do:
1) Actually build the function that looks for the about link and include it (easy to be basic, difficult to be very accurate)

2) Submit "Modified Date" to Drupal. This is really hard because there are a couple of methods that we use to look for dates... either from the document object OR from somewhere on the page if that doesn't exist. This means we can get the date in many different formats. Drupal will only accept one format, which is a unix timestamp. JS can convert a Date() object into a unix timestamp readily enough but constructing the proper date object with unknown input is going to be really difficult.

What should we do here? We could narrow the ways in which we search for modified date on the page, or we could turn the Drupal field into a text field that doesn't validate for date.

**Comment by bmoreinis** [comment]
There will be sites that don't work.  I'm going to close this issue and merge to master for now - and address sites not working in separate issues.
