### ISSUE TITLE
Date Modified

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#45]
>  turn the Drupal field into a text field that doesn't validate for date.
Let's convert this to MM/DD/YYYY and leave it as a simple text field.  If there is no value students will need to look one up, and key it in themselves. 

The goal is to find out when the page was updated ... Modified Date may not give us as accurate information as anything displayed on the page.  No need to have both fields.

**Comment by elisseck** [comment]
Not really sure what no need to have both fields is referring to. I've only ever know the one field.

**Comment by bmoreinis** [comment]
If students see a date field in the text by the byline, they will want to enter that somewhere.  The server's date modified value for the html file will auto-fill if it exists, but often it won't because it's a database-driven site.  So why have two fields, since the user-displayed date modified will supersede?

**Comment by elisseck** [comment]
Sorry i'm just really out of the loop on this one I think... maybe we talk about it in person and I will get it.

My understanding is that currently, we only have one field. We do not have two fields.
