### ISSUE TITLE
Page Links often misses things like citations and references

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#5]
Currently, page links only pulls links out of P tags.

Should this be expanded to cover some other tabs?

We are trying to avoid pulling anchor links, menu links, user links, and that sort of junk... but we would like to get citations and/or references for sure... which usually seem to appear in OL or UL.

If we just grab OL and/or UL we are likely to get a bunch of menu links we don't want. Ideas?

**Comment by bmoreinis** [comment]
I think that people can visually see link lists at the bottom of 
articles as citations.  It's handy, though, to grab links that are 
embedded in paragraphs as highlighted text.  I think it was brilliant of 
you to specify links within p tags!

**Comment by elisseck** [comment]
If it covers what you see as the need, i'll just close this issue then! At a later date we can think about whether we should mention in instruction docs or whatever that the auto-populated list will usually miss lists of references or citations as a reminder.

**Comment by bmoreinis** [comment]
User Documentation: 
https://docs.google.com/document/d/1d4qmuhJyILGs2YLCx8e-p7BDycmkQm7NxbsHef_-w0A/edit?usp=sharing
