### ISSUE TITLE
Page links field format not intuitive in blank form

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#6]
If you request a blank form, the page links field is just a short text field that makes it look like it will only accept one value.

If we are accepting multiple values (I assume we want to), that field should be made larger. It could probably use some help text for formatting like "comma separated list of links" or something so more users pass whatever validation we put the input through before sending it to to db.

**Comment by bmoreinis** [comment]
Yes, we should have the user enter the number of link spaces they want 
to complete in the form (with a default value of 3), and then 
auto-create those spaces for form generation.  This goes for any 
multiple-response categories.

**Comment by bmoreinis** [comment]
This was fixed last week.

**Comment by elisseck** [comment]
Thank you for closing the issues I forgot to close today!

I don't believe this particular one is fixed though.. unless i'm missing it. Testing master branch I still see just 1 text field when I load a blank form. Maybe I made a confusing commit note but I think this should get re-opened as a reminder.

I think the strategy will have to be a bit different because the form will already be generated when the user wants to "add more" link fields - I don't think it makes sense to put the choice in the popup before they get a chance to see what the form looks like (at least for first-run ux).

My idea is to start with just the one link field in a blank form that we have, and add a button to 'add another' inserts another blank field. We could check for a # of fields that exist before creating if we want to set a max. Thoughts?

**Comment by bmoreinis** [comment]
Oh - OOPS!  I thought this was the one about having multiple return fields when form was filled.  I get it.  I'll do that now.  Check out the new code, BTW!  V is just regular variable fields; VL is link fields (that make links clickable).

**Comment by bmoreinis** [comment]
Okay, I've added an 'Add Link" button and a "Hello World" script (at the very top of content.js).  That "Hello World" script can go away - in place (I THINK) needs to be whatever script actually creates a new form field.  Can I leave that to you?

**Comment by elisseck** [comment]
Cool - I haven't gotten the commit yet with those changes but sounds good - I will make the button do what it is supposed to do :)

**Comment by bmoreinis** [comment]
Thanks!

I basically get no feedback from GitHub when I do a commit.

I experience this latency where I commit things and GitHub doesn't 
recognize it for a few minutes.  Do you get that as well?

I DID just turn on 'Include your own updates" in Email Notification 
preferences, so that will calm me down some ... :-)

-Bram

**Comment by elisseck** [comment]
I'm not getting a delay like that - how are you committing and pushing? Git gui?

I am using the git bash CLI with cygwin to do my git work.

I wouldn't think that makes a difference but maybe it does?

**Comment by bmoreinis** [comment]
Yes, Git GUI. Maybe it does.
