### ISSUE TITLE
On latest Branch, "Better Directions" - Bad Message on About Links

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#64]
Says "Undefined" - should say 

return "We could not find any about links";

Why doesn't it?

**Comment by bmoreinis** [comment]
This is still a problem.  Maybe I overwrote your fix....

**Comment by elisseck** [comment]
Oops. I think I had done the wrong thing. Pushed a hot fix to master it was just one line. Should be working now.
