### ISSUE TITLE
ASAP: Load Form Export Over Form for Copy/Paste

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#82]
Enable students to copy/paste data from form, with headings and links formatted, as an alternative to saving as a Google Doc.  This enables schools that do not use Google, or do not wish to give the plugin drive-writing permission, to use the extension.

**Comment by deltafactory** [comment]
The download/export option uses json now, but I think it could export the
HTML version used to generate the Google doc almost as easily.

**Comment by deltafactory** [comment]
Addressed in #83, #91.
